= Delete Workshop Environment
:toc:
:icons:
:linkattrs:
:imagesdir: ../../resources/images


== Summary

This section will delete the workshop environment.

== Duration

NOTE: It will take approximately 5 minutes to complete this section.


== Step-by-step Guide

TIP: We need to manually delete the AWS resources created outside the CloudFormation template (e.g. the CloudWatch alarm). All other AWS resources created in the workshop environment will be deleted when you delete the CloudFormation stack.

=== Delete the *High throughput alarm* from *CloudWatch*

IMPORTANT: Read through all steps below before continuing.

. Open the link:https://console.aws.amazon.com/cloudwatch/[Amazon CloudWatch] console.
+
TIP: *_Context-click (right-click)_* the link above and open the link in a new tab or window to make it easy to navigate between this github workshop and AWS console.
+
. Make sure you are in the same *AWS Region* where you *_created_* your workshop environment.
. *_Select_* *Alarms* from the left navigation pane.
. *_Click_* the *check box* next to the *High throughput alarm - fs-...* alarm.
. *_Click_* the *Actions* button then *Delete*.
. *_Click_* *Delete* to confirm you want to delete the *High throughput alarm - fs-...* alarm.


=== Delete *Workshop Environment* via CloudFormation

IMPORTANT: Read through all steps below before continuing.

. Open the link:https://console.aws.amazon.com/cloudformation/[Amazon CloudFormation] console.
+
TIP: *_Context-click (right-click)_* the link above and open the link in a new tab or window to make it easy to navigate between this github workshop and AWS console.
+
. Make sure you are in the same *AWS Region* where you *_created_* your workshop environment.
. *_Click_* the *radio button* next to the *fsx-lustre-workshop* master or parent stack.
+
TIP: The master template will have the Stack name *fsx-lustre-workshop* without the nested label.
+
. *_Click_* the *Actions* button then *Delete stack*.
. *_Click_* *Yes, Delete* to delete the workshop environment.

IMPORTANT: It may take approximately 5 minutes to delete all AWS resources created by the CloudFormation template. Check the status periodically to verify all resources have been delete.



