= Tear down the workshop resources
:icons:
:linkattrs:
:imagesdir: ../resources/images

*Congratulation!* You have completed the Amazon FSx for NetApp ONTAP Workshop.

== Duration

NOTE: It will take approximately 15 minutes to complete this section.  If the SnapLock portion of the Data Protection section was done, you must wait 2 hours after completing those steps before proceeding.  This allows enough time for the SnapLock retention periods to expire and the file systems to be deleted.

=== Delete Resources Created During Workshop

WARNING: You will be unable to delete the FSx for NetApp ONTAP file system for 2 hours if you completed the SnapLock portion of the Data Protection section.  This is because this portion protected several files with WORM (Write Once Read Many) capability making them immutable.  Once 2 hours have past since the completion of that portion of the workshop, you can proceed with deleting the file system and other resources following the steps below.

. *_Run_* the command below to SSH to the cluster management endpoint of your *DR/Secondary* FSx for ONTAP file system.

+
TIP: If the *Session Manager* window has timed out, e.g. the session is unresponsive, close the session window and create a new one. Return to the link:https://console.aws.amazon.com/ec2/[Amazon EC2] console. *_Click_* the radio button next to the instance with the name *FSx for ONTAP Workshop Linux Instance*. *_Click_* the *Connect* button. Connect using AWS Systems Manager - *_Select_* *Session Manager* tab and *_click_* the Connect button to open a session in your browser.  Change the shell back to bash by typing the command ***bash*** and then return.
+

+
[source,bash]
----
ssh ${ADMINUSER}@${DRMGMTENDPOINT}
----
+

. *_Run_* the below command to turn off ONTAP CLI confirmations.
+
[source,bash]
----
set -confirmations off
----
+

. *_Run_* the below command to delete the volume created during the FlexCache section of the workshop.
+
[source,bash]
----
volume unmount -vserver svm01-dr -volume cachevol
volume offline -vserver svm01-dr -volume cachevol
volume flexcache delete -vserver svm01-dr -volume cachevol
----

=== Delete Workshop Environment via CloudFormation

IMPORTANT: Read through all steps below before continuing.  Ensure that all of the volume deletes above have completed and are not still in a status of deleting.

. Open the link:https://console.aws.amazon.com/cloudformation/[Amazon CloudFormation] console.
+
TIP: *_Context-click (right-click)_* the link above and open the link in a new tab or window to make it easy to navigate between this GitHub workshop and AWS console.
+
. Make sure you are in the same *AWS Region* where you *_created_* your workshop environment.
. *_Click_* the *radio button* next to the *ontap* stack.
. *_Click_* the *Actions* button then *Delete stack*.
. *_Click_* *Yes, Delete* to delete the workshop environment.
+
IMPORTANT: It may take approximately 90 minutes to delete all AWS resources created by the CloudFormation template. Check the status periodically to verify all resources have been delete.
+
. Once CloudFormation has successfully deleted the parent and nested stacks for the workshop, *_return_* to the link:https://console.aws.amazon.com/fsx/[Amazon FSx] console in the region you deployed the workshop.  *_Click_* *Backups* on the left, and delete any remaining backups which were created during the workshop which will be of type *User-Initiated*.