---
AWSTemplateFormatVersion: 2010-09-09

Description: Creates the Amazon FSx for Lustre workshop environment.

Metadata:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com) and Aaron Dailey (aaronda@amazon.com)
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Workshop Environment
      Parameters:
        - VpcCidr
        - AvailabilityZones
        - KeyName
        - EmailAddress
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      KeyName:
        default: EC2 key pair
      EmailAddress:
        default: Email Address
      VpcCidr:
        default: VPC CIDR

Parameters:
  AvailabilityZones:
    Description: Select two (2) Availability Zones (AZ). One public subnet and one private subnet will be created in each AZ.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  EmailAddress:
    Description: The email address for CloudWatch alarm notification.
    Type: String
  KeyName:
    Description: Select the EC2 key pair for the Linux instance (Lustre client).
    Type: AWS::EC2::KeyPair::KeyName
  VpcCidr:
    AllowedValues: 
    - 10.0.0.0/16
    - 173.31.0.0/16
    - 192.168.0.0/16
    Default: 10.0.0.0/16
    Description: Select the private IPv4 CIDR for the VPC.
    Type: String
  LatestLinuxAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2'

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AZ0:
          !Select [ 0, !Ref AvailabilityZones ]
        AZ1:
          !Select [ 1, !Ref AvailabilityZones ]
        VpcCidr:
          !Ref VpcCidr
      TemplateURL: https://amazon-fsx.s3.amazonaws.com/workshop/lustre/templates/01-vpc.yaml
  FileSystem:
    DependsOn: [ Vpc ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DefaultSecurityGroupId:
          !GetAtt [ Vpc, Outputs.DefaultSecurityGroupId ]
        SubnetId:
          !GetAtt [ Vpc, Outputs.PrivateSubnetId0 ]
      TemplateURL: https://amazon-fsx.s3.amazonaws.com/workshop/lustre/templates/02-file-system.yaml
  LinuxInstance:
    DependsOn: [ FileSystem ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        LatestLinuxAmiId:
          !Ref LatestLinuxAmiId
        KeyName:
          !Ref KeyName
        FileSystemId:
          !GetAtt [ FileSystem, Outputs.FileSystemId ]
        DefaultSecurityGroupId:
          !GetAtt [ Vpc, Outputs.DefaultSecurityGroupId ]
        SubnetId:
          !GetAtt [ Vpc, Outputs.PrivateSubnetId0 ]
      TemplateURL: https://amazon-fsx.s3.amazonaws.com/workshop/lustre/templates/03-linux-instance.yaml
  Dashboard:
    DependsOn: [ FileSystem ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EmailAddress:
          !Ref EmailAddress
        FileSystemId:
          !GetAtt [ FileSystem, Outputs.FileSystemId ]
      TemplateURL: https://amazon-fsx.s3.amazonaws.com/workshop/lustre/templates/04-dashboard.yaml


